### ISSUE TITLE
Memory errors revealed by AFL++, small batch 6

### ISSUE THREAD

**Issue by debrouxl** [libxmp/libxmp#268]
Besides the new ProWizard sample I've posted in #256 , a new heap-based OOB write which still trips a build of HEAD @ f749061f66907bf29698aa7796a556cf06faade1 + the combined patch for #266 was found yesterday . This one is almost certainly brand-new: it crashes in a source file not previously hit during this fuzzing run, so it looks that the fuzzer eventually slowly managed to corrupt an OXM file the right way.

```
Loading output/3/crashes/id:000544,sig:06,src:015778,time:657866295,op:havoc,rep:4 (1 of 1)
=================================================================
==2194381==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6250000050fe at pc 0x7f20f36f4902 bp 0x7fff5628da50 sp 0x7fff5628da48
WRITE of size 8 at 0x6250000050fe thread T0
    #0 0x7f20f36f4901 in copy_samples .../xmp/libxmp/src/depackers/vorbis.c:4975:15
    #1 0x7f20f36f4901 in convert_samples_short .../xmp/libxmp/src/depackers/vorbis.c:5061:10
    #2 0x7f20f36f4901 in stb_vorbis_get_frame_short .../xmp/libxmp/src/depackers/vorbis.c:5078:7
    #3 0x7f20f36f4cc2 in stb_vorbis_get_frame_short_interleaved .../xmp/libxmp/src/depackers/vorbis.c:5116:27
    #4 0x7f20f36f4cc2 in stb_vorbis_decode_memory .../xmp/libxmp/src/depackers/vorbis.c:5232:15
    #5 0x7f20f36d7e45 in oggdec .../xmp/libxmp/src/depackers/oxm.c:162:6
    #6 0x7f20f36d7e45 in decrunch_oxm .../xmp/libxmp/src/depackers/oxm.c:293:14
    #7 0x7f20f358478e in decrunch .../xmp/libxmp/src/load.c:221:7
    #8 0x7f20f358551f in xmp_load_module .../xmp/libxmp/src/load.c:571:6
    #9 0x4cee43 in main .../xmp/xmp-cli/src/main.c:399:9
    #10 0x7f20f309ed09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #11 0x420679 in _start (.../bin/xmp+0x420679)

0x6250000050fe is located 2 bytes to the left of 8192-byte region [0x625000005100,0x625000007100)
allocated by thread T0 here:
    #0 0x49a6ed in malloc (.../bin/xmp+0x49a6ed)
    #1 0x7f20f36f4c2f in stb_vorbis_decode_memory .../xmp/libxmp/src/depackers/vorbis.c:5226:21
    #2 0x7f20f36d7e45 in oggdec .../xmp/libxmp/src/depackers/oxm.c:162:6
    #3 0x7f20f36d7e45 in decrunch_oxm .../xmp/libxmp/src/depackers/oxm.c:293:14
    #4 0x7f20f358478e in decrunch .../xmp/libxmp/src/load.c:221:7
    #5 0x7f20f358551f in xmp_load_module .../xmp/libxmp/src/load.c:571:6
    #6 0x4cee43 in main .../xmp/xmp-cli/src/main.c:399:9
    #7 0x7f20f309ed09 in __libc_start_main csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: heap-buffer-overflow .../xmp/libxmp/src/depackers/vorbis.c:4975:15 in copy_samples
```

[libxmp_asan_crashers_20201210_02.tar.gz](https://github.com/libxmp/libxmp/files/5673927/libxmp_asan_crashers_20201210_02.tar.gz)

**Comment by AliceLR** [comment]
Thanks. A missing error return value check in `stb_vorbis_decode_memory` was causing it to set the current offset to -1, hence the out-of-bounds write.
