### ISSUE TITLE
OSS-Fuzz and/or libFuzzer integration.

### ISSUE THREAD

**Issue by AliceLR** [libxmp/libxmp#302]
Quoting @debrouxl from #299:
> After the 4.5.0 release is cut, maybe libxmp could now be integrated into https://github.com/google/oss-fuzz without being drowned in bug reports ? All the more libxmp already has both a filename-based loading API which is usually used to run simple CLI front-ends through afl-fuzz and honggfuzz, and a memory-based loading API used by a libfuzzer-based fuzzer.

[Relevant link on preparing for OSS-Fuzz integration](https://google.github.io/oss-fuzz/getting-started/new-project-guide/) and [for getting a project accepted](https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/).

> To be accepted to OSS-Fuzz, an open-source project must have a significant user base and/or be critical to the global IT infrastructure.

Not sure how well libxmp qualifies there but IMO it's worth a shot anyway. The first step towards this would be creating a libFuzzer endpoint.

**Comment by debrouxl** [comment]
Yeah, "significant user base" would probably be hard to prove indeed... For what that is worth, libxmp barely registers on Debian popcon, whereas libmodplug and libopenmpt rank much higher.

**Comment by debrouxl** [comment]
I took a whack at implementing a libfuzzer front-end, using `test_api_load_module_from_memory.c` as a starting point. I stored that file named `libfuzzer.c` in the test-dev directory; nothing fancy in there:
```
#include <stdint.h>
#include <stddef.h>
#include "../include/xmp.h"

int LLVMFuzzerTestOneInput(const uint8_t * data, size_t size)
{
	xmp_context opaque;
	int ret;

	opaque = xmp_create_context();
	ret = xmp_load_module_from_memory(opaque, data, size);
	xmp_free_context(opaque);
	return ret;
}
```

Building and running this program from the test-dev directory, for now outside the integration to the build system `Makefile.in`, is equally straightforward:
```
clang -O3 -fsanitize=fuzzer,address,undefined -o libfuzzer -L ../lib -lxmp libfuzzer.c
LD_LIBRARY_PATH=../lib ./libfuzzer <options, e.g. -max_len=<value>, see https://llvm.org/docs/LibFuzzer.html >
```

Er... it looks like there's an oversight in the memory-mapped I/O functions ? :)
```
$ LD_LIBRARY_PATH=../lib ./libfuzzer 
INFO: Seed: 2981652074
INFO: Loaded 1 modules   (1 inline 8-bit counters): 1 [0x5a9ef0, 0x5a9ef1), 
INFO: Loaded 1 PC tables (1 PCs): 1 [0x56d5e8,0x56d5f8), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
=================================================================
==454661==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000091 at pc 0x0000005217d7 bp 0x7fff8c0f35d0 sp 0x7fff8c0f2d98
READ of size 17 at 0x602000000091 thread T0
    #0 0x5217d6 in __asan_memcpy (.../xmp/libxmp/test-dev/libfuzzer+0x5217d6)
    #1 0x7f0aba23d22f in mread .../xmp/libxmp/src/memio.c:63:2
    #2 0x7f0aba239550 in hio_read .../xmp/libxmp/src/hio.c:242:9
    #3 0x7f0aba24b6de in xm_test .../xmp/libxmp/src/loaders/xm_load.c:52:6
    #4 0x7f0aba2367fc in load_module .../xmp/libxmp/src/load.c:457:17
    #5 0x7f0aba237320 in xmp_load_module_from_memory .../xmp/libxmp/src/load.c:654:8
    #6 0x551fcd in LLVMFuzzerTestOneInput (.../xmp/libxmp/test-dev/libfuzzer+0x551fcd)
    #7 0x45b6c1 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (.../xmp/libxmp/test-dev/libfuzzer+0x45b6c1)
    #8 0x45cb36 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (.../xmp/libxmp/test-dev/libfuzzer+0x45cb36)
    #9 0x45cfa9 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (.../xmp/libxmp/test-dev/libfuzzer+0x45cfa9)
    #10 0x44ccb5 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (.../xmp/libxmp/test-dev/libfuzzer+0x44ccb5)
    #11 0x474902 in main (.../xmp/libxmp/test-dev/libfuzzer+0x474902)
    #12 0x7f0ab9e9dd09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #13 0x4214d9 in _start (.../xmp/libxmp/test-dev/libfuzzer+0x4214d9)

0x602000000091 is located 0 bytes to the right of 1-byte region [0x602000000090,0x602000000091)
allocated by thread T0 here:
    #0 0x52237d in malloc (.../xmp/libxmp/test-dev/libfuzzer+0x52237d)
    #1 0x435467 in operator new(unsigned long) (.../xmp/libxmp/test-dev/libfuzzer+0x435467)
    #2 0x45cb36 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (.../xmp/libxmp/test-dev/libfuzzer+0x45cb36)
    #3 0x45cfa9 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (.../xmp/libxmp/test-dev/libfuzzer+0x45cfa9)
    #4 0x44ccb5 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (.../xmp/libxmp/test-dev/libfuzzer+0x44ccb5)
    #5 0x474902 in main (.../xmp/libxmp/test-dev/libfuzzer+0x474902)
    #6 0x7f0ab9e9dd09 in __libc_start_main csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: heap-buffer-overflow (.../xmp/libxmp/test-dev/libfuzzer+0x5217d6) in __asan_memcpy
Shadow bytes around the buggy address:
  0x0c047fff7fc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff8000: fa fa 00 00 fa fa 00 fa fa fa 00 fa fa fa 00 fa
=>0x0c047fff8010: fa fa[01]fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==454661==ABORTING
MS: 0 ; base unit: 0000000000000000000000000000000000000000


artifact_prefix='./'; Test unit written to ./crash-da39a3ee5e6b4b0d3255bfef95601890afd80709
Base64: 
```

clang 11 on Debian sid amd64 here.

**Comment by sezero** [comment]
I don't do libfuzzer or anything that fancy, I use plain old valgrind:

```
$ cat 0.c
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include <xmp.h>

int LLVMFuzzerTestOneInput(void *data, size_t size)
{
	xmp_context opaque;
	int ret;

	opaque = xmp_create_context();
	ret = xmp_load_module_from_memory(opaque, data, size);
	xmp_free_context(opaque);
	return ret;
}

int main (void) {
	int r;
#if 0
	int buf[3];
	int i;

	srand(time(NULL));
	for (i = 0; i < 3; ++i) {
		buf[i] = rand();
	}
#else
	char c = *(char*)&r;
	char *buf = &c;
#endif

	r = LLVMFuzzerTestOneInput(buf, 1);

	return r;
}
```

0 size is _BAD_: https://github.com/libxmp/libxmp/blob/master/src/load.c#L639

However, with size == 1 (or 12, if I change `#if 0` to `#if 1`) I can't see any crashes
on my i686-Linux (CentOS 6.10).

**Comment by AliceLR** [comment]
The initial implementation of this has been merged. Fuzzing for the playercode and possibly other API functions should still be added at some point, but the fuzzers are still finding bugs in the loaders and depackers.
